#!/usr/bin/env python

import rospy
import cv2
from geometry_msgs.msg import Twist
import time

def controller():
	msg=Twist()
	pub=rospy.Publisher('/cmd_vel',Twist,queue_size=10)
	rospy.init_node('robot_talker',anonymous=True)

	j = 1
	while j <= 5:
		msg.angular.z=0
		msg.linear.x = .4
		pub.publish(msg)
		time.sleep(2)
		j = j+1

	time.sleep(19)
	k = 1
	while k <= 5:
		msg.angular.z=.4
		msg.linear.x = .4
		pub.publish(msg)
		time.sleep(1)
		k = k+1

	time.sleep(2.5)
	l = 1
	while l <= 5:
		msg.angular.z=0
		msg.linear.x = .4
		pub.publish(msg)
		time.sleep(2)
		l = l+1

	n = 1
	while n <= 5:
		msg.angular.z=0
		msg.linear.x = .4
		pub.publish(msg)
		time.sleep(6)
		n = n+1

	
	m = 1
	while m <= 5:
		msg.angular.z=0
		msg.linear.x = 0
		pub.publish(msg)
		time.sleep(5)
		m = m+1
if __name__== '__main__':
	controller()
